# Generated by Django 6.1.1 on 2026-09-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_historicalproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproduto',
            name='imagem',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='imagem'),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='imagem'),
        ),
    ]
