services:
    django:
        build: .
        ports:
            - "8000:8000"
        volumes:
            - ./db.sqlite3:/app/db.sqlite3
        depends_on:
            - redis_cache
        restart: unless-stopped

    redis_cache:
        image: redis:7-alpine
        ports:
            - "6380:6379" # Host 6380 -> Container 6379
        restart: unless-stopped
