# Generated by Django 6.1.1 on 2026-09-11 00:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('criado', 'Criado'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='criado', max_length=20, verbose_name='status')),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='valor total')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('usuario', models.ForeignKey(help_text='Usuário que registrou ou autorizou o pedido para auditoria.', on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='usuário responsável')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='número da parcela')),
                ('total_parcelas', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='total de parcelas')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='valor')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='valor pago')),
                ('vencimento', models.DateField(verbose_name='vencimento')),
                ('meio_pagamento', models.CharField(blank=True, choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('cartao_debito', 'Cartão de débito'), ('cartao_credito', 'Cartão de crédito'), ('boleto', 'Boleto'), ('transferencia', 'Transferência bancária'), ('outro', 'Outro')], max_length=20, null=True, verbose_name='meio de pagamento')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='pendente', max_length=10, verbose_name='status')),
                ('pago_em', models.DateTimeField(blank=True, null=True, verbose_name='pago em')),
                ('observacao', models.TextField(blank=True, verbose_name='observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_receber', to='vendas.pedido', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'conta a receber',
                'verbose_name_plural': 'contas a receber',
                'ordering': ['vencimento', 'numero_parcela'],
            },
        ),
        migrations.AddIndex(
            model_name='pedido',
            index=models.Index(fields=['status', 'criado_em'], name='pedido_status_data_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['status', 'vencimento'], name='conta_status_venc_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['pedido', 'numero_parcela'], name='conta_pedido_parc_idx'),
        ),
        migrations.AddConstraint(
            model_name='contareceber',
            constraint=models.UniqueConstraint(fields=('pedido', 'numero_parcela'), name='parcela_unica_por_pedido'),
        ),
    ]
